# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='golf_groups',
            new_name='groups',
        ),
        migrations.AddField(
            model_name='userdata',
            name='has_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='invite_name',
            field=models.CharField(default='empty', max_length=1000),
        ),
        migrations.AddField(
            model_name='userdata',
            name='invite_type',
            field=models.BooleanField(default=False),
        ),
    ]
