# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0002_auto_20160425_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='members',
        ),
        migrations.AddField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(related_name='_groups_members_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='groups',
        ),
        migrations.AddField(
            model_name='userdata',
            name='groups',
            field=models.ManyToManyField(to='Users.Groups'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
