# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfevent',
            name='group',
        ),
    ]
